name: Hello
on:
  push:
jobs:
  greet:
    runs-on: ubuntu-latest 
    steps:
      - name: checking the code
        uses: actions/checkout@v7
      - name: say hello
        run: echo "Hello from GitHub Actions!"
