name: Hello-2
on:
  workflow_call:
jobs:
  greet:
    runs-on: ubuntu-latest 
    steps:
      - name: checking the code
        uses: actions/checkout@v7
      - name: say hello
        run: echo "Hello from GitHub Actions!"
      - name: print current date and time
        run: date
      - name: print branch name
        run: |
          echo "Branch name: ${{ github.ref_name }}"
      - name: list files in the repository
        run: ls -la
      - name: print runner operating system
        run: |
          echo "Runner OS: ${{ runner.os }}"
        
