name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter environment (staging/production)"
        required: true
        default: staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
