name: prcheck
on:
  schedule:
    - cron: '26 0 * * *'  

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: PR check running for branch
        run: echo "PR check running for branch ${{ github.head_ref }}"
